-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
ITEM_MAPPING = {
    [1] = {"GoalComp", "toggle"},
    [2] = {"MainQuestProg", "consumable"},
    [3] = {"FactionComplete", "consumable"},
    [4] = {"CompanionProg", "consumable"},
    [5] = {"CollegeProg", "consumable"},
    [6] = {"GuildProg", "consumable"},
    [7] = {"BrotherProg", "consumable"},
    [8] = {"DawnProg", "consumable"},
    [9] = {"DragProg", "consumable"},
    [10] = {"Conjuration", "toggle"},
    [11] = {"Destruction", "toggle"},
    [12] = {"Archery", "toggle"},
    [13] = {"OneHanded", "toggle"},
    [14] = {"TwoHanded", "toggle"},
    [15] = {"Speech","toggle"},
    [16] = {"Alteration","toggle"},
    [17] = {"Restoration","toggle"},
    [18] = {"Block","toggle"},
    [19] = {"HeavyArmor","toggle"},
    [20] = {"LightArmor","toggle"},
    [21] = {"Sneak","toggle"},
    [22] = {"Enchanting","toggle"},
    [23] = {"Illusion","toggle"},
    [24] = {"Smithing","toggle"},
    [25] = {"Alchemy","toggle"},
    [26] = {"Lockpicking","toggle"},
    [27] = {"Pickpocket","toggle"},
    [28] = {"WeaponProg","consumable"},    
    [29] = {"SpellProg","consumable"},
    [30] = {"LightArmProg","consumable"},
    [31] = {"HeavyArmProg","consumable"},
    [32] = {"ThalmorEars","consumable"}
}