-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
LOCATION_MAPPING = {
    [2] = {"@Province Locations/Helgen/Unbound"},
    [3] = {"@Province Locations/Riverwood/Before the Storm"},
    [4] = {"@Province Locations/Whiterun/Bleak Falls Barrow"},
    [5] = {"@Province Locations/Whiterun/Dragon Rising"},
    [6] = {"@Province Locations/High Hrothgar/Way of the Voice"},
    [7] = {"@Province Locations/High Hrothgar/Horn of Jurgen Windcaller Note"},
    [8] = {"@Province Locations/Riverwood/Blade in the Dark"},
    [9] = {"@Province Locations/High Hrothgar/Jurgen Horn Returned"},
    [10] = {"@Province Locations/Riverwood/Diplomatic Immunity"},
    [11] = {"@Province Locations/Riverwood/A Cornered Rat"},
    [12] = {"@Province Locations/Riverwood/Alduin's Wall"},
    [13] = {"@Province Locations/High Hrothgar/Throat of the World"},
    [14] = {"@Province Locations/High Hrothgar/Elder Knowledge"},
    [15] = {"@Province Locations/High Hrothgar/Alduin's Bane"},
    [16] = {"@Province Locations/High Hrothgar/The Fallen"},
    [17] = {"@Province Locations/Whiterun/The World-Eater's Eyrie"},

    [18] = {"@Province Locations/The Companions/Take Up Arms"},
    [19] = {"@Province Locations/The Companions/Proving Honor"},
    [20] = {"@Province Locations/The Companions/The Silver Hand"},
    [21] = {"@Province Locations/The Companions/Blood's Honor"},
    [22] = {"@Province Locations/The Companions/Purity of Revenge"},
    [23] = {"@Province Locations/The Companions/Glory of the Dead"},

    [24] = {"@Province Locations/The College of Winterhold/First Lessons"},
    [25] = {"@Province Locations/The College of Winterhold/Under Saarthal"},
    [26] = {"@Province Locations/The College of Winterhold/Hitting the Books"},
    [27] = {"@Province Locations/The College of Winterhold/Good Intentions"},
    [28] = {"@Province Locations/The College of Winterhold/Revealing the Unseen"},
    [29] = {"@Province Locations/The College of Winterhold/Containment"},
    [30] = {"@Province Locations/The College of Winterhold/Staff of Magnus"},
    [31] = {"@Province Locations/The College of Winterhold/Eye of Magnus"},

    [32] = {"@Province Locations/The Thieves' Guild/Chance Arrangement"},
    [33] = {"@Province Locations/The Thieves' Guild/Taking Care of Business"},
    [34] = {"@Province Locations/The Thieves' Guild/Loud and Clear"},
    [35] = {"@Province Locations/The Thieves' Guild/Dampened Spirits"},
    [36] = {"@Province Locations/The Thieves' Guild/Scoundrels Folly"},
    [37] = {"@Province Locations/The Thieves' Guild/Speaking with Silence"},
    [38] = {"@Province Locations/The Thieves' Guild/Hard Answers"},
    [39] = {"@Province Locations/The Thieves' Guild/Pursuit"},
    [40] = {"@Province Locations/The Thieves' Guild/Trinity Restored"},
    [41] = {"@Province Locations/The Thieves' Guild/Blindsighted"},
    [42] = {"@Province Locations/The Thieves' Guild/Darkness Returns"},

    [43] = {"@Province Locations/Windhelm/Innocence Lost"},
    [44] = {"@Province Locations/Abandoned Shack/With Friends like These"},
    [45] = {"@Province Locations/Dark Brotherhood Sanctuary/Sanctuary"},
    [46] = {"@Province Locations/Dark Brotherhood Sanctuary/Mourning Never Comes"},
    [47] = {"@Province Locations/Dark Brotherhood Sanctuary/Whispers in the Dark"},
    [48] = {"@Province Locations/Dark Brotherhood Sanctuary/The Silence Has Been Broken"},
    [49] = {"@Province Locations/Dark Brotherhood Sanctuary/Bound Until Death"},
    [50] = {"@Province Locations/Dark Brotherhood Sanctuary/Breaching Security"},
    [51] = {"@Province Locations/Dark Brotherhood Sanctuary/The Cure for Madness"},
    [52] = {"@Province Locations/Dark Brotherhood Sanctuary/Recipe for Disaster"},
    [53] = {"@Province Locations/Dark Brotherhood Sanctuary/To Kill an Empire"},
    [54] = {"@Province Locations/Dark Brotherhood Sanctuary/Death Incarnate"},
    [55] = {"@Province Locations/Dark Brotherhood Sanctuary/Hail Sithis!"},

    [56] = {"@Province Locations/Fort Dawnguard/Dawnguard"},
    [57] = {"@Province Locations/Fort Dawnguard/Awakening"},
    [58] = {"@Province Locations/Fort Dawnguard/Bloodline"},
    [59] = {"@Province Locations/Fort Dawnguard/A New Order"},
    [60] = {"@Province Locations/Fort Dawnguard/Prophet"},
    [61] = {"@Province Locations/Fort Dawnguard/Scroll Scouting"},
    [62] = {"@Province Locations/Fort Dawnguard/Chasing Echoes"},
    [63] = {"@Province Locations/Fort Dawnguard/Seeking Disclosure"},
    [64] = {"@Province Locations/Ancestor Glade/Unseen Visions"},
    [65] = {"@Province Locations/The Forgotten Vale/Touching the Sky"},
    [66] = {"@Province Locations/Fort Dawnguard/Kindred Judgment"},

    [67] = {"@Province Locations/Windhelm/Dragonborn"},
    [68] = {"@Province Locations/Solstheim/The Temple of Miraak"},
    [69] = {"@Province Locations/Solstheim/The Fate of the Skaal"},
    [70] = {"@Province Locations/Solstheim/Cleansing the Stones"},
    [71] = {"@Province Locations/Solstheim/The Path of Knowledge"},
    [72] = {"@Province Locations/Solstheim/The Gardener of Men"},
    [73] = {"@Province Locations/Solstheim/At the Summit of Apocrypha"},

    [74] = {"@Province Locations/Azura's Shrine/The Black Star"},
    [75] = {"@Province Locations/Markarth/The House of Horrors"},
    [76] = {"@Province Locations/Falkreath/Ill Met by Moonlight"},
    [77] = {"@Province Locations/Solitude/The Mind of Madness"},
    [78] = {"@Province Locations/Markarth/The Taste of Death"},
    [79] = {"@Province Locations/Dawnstar/Waking Nightmare"},

    [80] = {"@Province Locations/Statue to Meridia/The Break of Dawn"},
    [81] = {"@Province Locations/Largashbur/The Cursed Tribe"},
    [82] = {"@Province Locations/Falkreath/A Daedra's Best Friend"},
    [83] = {"@Province Locations/Rorikstead/A Night to Remember"},
    [84] = {"@Province Locations/Shrine to Peryite/The Only Cure"},

    [85] = {"@Province Locations/Sacellum of Boethiah/Boethiah's Calling"},
    [86] = {"@Province Locations/The College of Winterhold/Discerning the Transmundane"},
    [87] = {"@Province Locations/Dawnstar/Pieces of the Past"},
    [88] = {"@Province Locations/Whiterun/The Whispering Door"},

    [89] = {"@Province Locations/Misc Objectives/Den Clearer"},
    [90] = {"@Province Locations/Misc Objectives/Punch-Out"},
    [91] = {"@Province Locations/Misc Objectives/Mandatory Maintenance"},
    [92] = {"@Province Locations/Misc Objectives/Dragons Slain = 2"},
    [93] = {"@Province Locations/Misc Objectives/Barovian Housekeeping"},
    [94] = {"@Province Locations/Misc Objectives/Skilled"},
    [95] = {"@Province Locations/Misc Objectives/Dragons Slain = 6"},
    [96] = {"@Province Locations/Misc Objectives/Crafter (5 Unique Items)"},
    [97] = {"@Province Locations/Misc Objectives/Dragons Slain = 10"},

    [98] = {"@Province Locations/Persistent Objectives/In a Pinch"},
    --[98] = {"@Province Locations/Fishery Quests/In a Pinch"},
    [99] = {"@Province Locations/Fishery Quests/Catch of the Day"},
    [100] = {"@Province Locations/Fishery Quests/Caught in the Rain"},
    [101] = {"@Province Locations/Fishery Quests/Crustacean Extermination"},
    [102] = {"@Province Locations/Fishery Quests/Frozen Fish"},
    [103] = {"@Province Locations/Fishery Quests/Tusked Terror"},

    [104] = {"@Province Locations/Persistent Objectives/Hunting Novice"},
    --[104] = {"@Province Locations/Hunting/Hunting Novice"},
    [105] = {"@Province Locations/Hunting/Hunting Skilled"},
    [106] = {"@Province Locations/Hunting/Hunting Expert"},
    [107] = {"@Province Locations/Hunting/Hunting Legendary"},

    [108] = {"@Province Locations/Persistent Objectives/Bandit Bounties = 3"},
    --[108] = {"@Province Locations/Bounties/Bandit Bounties = 3"},
    [109] = {"@Province Locations/Bounties/Bandit Bounties = 6"},
    [110] = {"@Province Locations/Bounties/Forsworn Bounties = 3"},
    [111] = {"@Province Locations/Bounties/Forsworn Bounties = 6"},
    [112] = {"@Province Locations/Bounties/Dragon Bounties = 3"},
    [113] = {"@Province Locations/Bounties/Dragon Bounties = 6"},

    [114] = {"@Province Locations/Persistent Objectives/Standing Stones Found = 4"},
    --[114] = {"@Province Locations/Exploration/Standing Stones Found = 4"},
    [115] = {"@Province Locations/Exploration/Standing Stones Found = 8"},
    [116] = {"@Province Locations/Exploration/Standing Stones Found = 13"},
    [117] = {"@Province Locations/Exploration/Word Wall Read = 1"},
    [118] = {"@Province Locations/Exploration/Word Walls Read = 3"},
    [119] = {"@Province Locations/Exploration/Word Walls Read = 6"},
    [120] = {"@Province Locations/Exploration/Miner Sixty-Niner"},
    [121] = {"@Province Locations/Exploration/Eminent Domain"},
    [122] = {"@Province Locations/Exploration/Archaeologist"},

    [123] = {"@Province Locations/Persistent Objectives/Townhomes Owned = 1"},
    --[123] = {"@Province Locations/Housing/Townhomes Owned = 1"},
    [124] = {"@Province Locations/Housing/Land Owned = 1"},
    [125] = {"@Province Locations/Housing/Townhomes Owned = 3"},
    [126] = {"@Province Locations/Housing/Land Owned = 3"},
    [127] = {"@Province Locations/Housing/Main Hall"},
    [128] = {"@Province Locations/Housing/Town Homes = 5"},
    [129] = {"@Province Locations/Housing/Full Manor on 1 Land"},

    [130] = {"@Province Locations/???/All Factions Complete"}
}
